#%RAML 1.0
title: twitter-prc-api
mediaType: application/json
baseUri: https://twitter-prc.us-e2.cloudhub.io/dev/api/
description: This API integrates with Twitter's API and is capable of performing some analysis on recent tweets

protocols:
  - HTTPS

securitySchemes:
  securityShceme:
    type: Basic Authentication
  oauth_2.0: !include /exchange_modules/68ef9520-24e9-4cf2-b2f5-620025690913/training-oauth20-security-scheme/1.0.2/OAuth2.raml

securedBy: [oauth_2.0]

/tweets:
  description: retrieves a list of tweets (max 10) that contain a key word in the last numhours
  get:
    queryParameters:
      keyword:
        description: the string the api will search for in tweets
        example: apple
        type: string
        required: true
      numHours:
        description: this restricts the time frame of tweets to be returned by the number of hours since its creation
        example: 2
        type: number
        required: true
      count:
        description: the number of tweets to pull from twitter's api
        example: 10
        type: number
        maximum: 10
        required: false
    responses:
      200: 
        body:
          applications/json:
            example: !include examples/listOfTweetInfo.json
              


/hashtags:
  description: retrieves a list of hastags used in the top 10 most popular tweets containing a keyword
  get:
    queryParameters:
      keyword:
        description: the string the api will search for in tweets
        example: apple
        type: string
        required: true
    responses:
      200: 
        body:
          applications/json:
            example: !include examples/listOfHashtags.json